//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class SUIFW_UITypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(SUIFW.UIType), typeof(System.Object));
		L.RegFunction("New", _CreateSUIFW_UIType);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("IsClearStack", get_IsClearStack, set_IsClearStack);
		L.RegVar("UIForms_Type", get_UIForms_Type, set_UIForms_Type);
		L.RegVar("UIForms_ShowMode", get_UIForms_ShowMode, set_UIForms_ShowMode);
		L.RegVar("UIForm_LucencyType", get_UIForm_LucencyType, set_UIForm_LucencyType);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSUIFW_UIType(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				SUIFW.UIType obj = new SUIFW.UIType();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: SUIFW.UIType.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_IsClearStack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SUIFW.UIType obj = (SUIFW.UIType)o;
			bool ret = obj.IsClearStack;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index IsClearStack on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UIForms_Type(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SUIFW.UIType obj = (SUIFW.UIType)o;
			int ret = obj.UIForms_Type;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index UIForms_Type on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UIForms_ShowMode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SUIFW.UIType obj = (SUIFW.UIType)o;
			int ret = obj.UIForms_ShowMode;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index UIForms_ShowMode on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UIForm_LucencyType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SUIFW.UIType obj = (SUIFW.UIType)o;
			int ret = obj.UIForm_LucencyType;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index UIForm_LucencyType on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_IsClearStack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SUIFW.UIType obj = (SUIFW.UIType)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.IsClearStack = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index IsClearStack on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_UIForms_Type(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SUIFW.UIType obj = (SUIFW.UIType)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.UIForms_Type = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index UIForms_Type on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_UIForms_ShowMode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SUIFW.UIType obj = (SUIFW.UIType)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.UIForms_ShowMode = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index UIForms_ShowMode on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_UIForm_LucencyType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SUIFW.UIType obj = (SUIFW.UIType)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.UIForm_LucencyType = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index UIForm_LucencyType on a nil value" : e.Message);
		}
	}
}

