--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.WXToken_pb')

WXTOKEN = protobuf.Descriptor();
WXTOKEN_ACCESS_TOKEN_FIELD = protobuf.FieldDescriptor();
WXTOKEN_EXPIRES_IN_FIELD = protobuf.FieldDescriptor();
WXTOKEN_REFRESH_TOKEN_FIELD = protobuf.FieldDescriptor();
WXTOKEN_OPENID_FIELD = protobuf.FieldDescriptor();
WXTOKEN_SCOPE_FIELD = protobuf.FieldDescriptor();
WXTOKEN_UNIONID_FIELD = protobuf.FieldDescriptor();
WXERROR = protobuf.Descriptor();
WXERROR_ERRCODE_FIELD = protobuf.FieldDescriptor();
WXERROR_ERRMSG_FIELD = protobuf.FieldDescriptor();

WXTOKEN_ACCESS_TOKEN_FIELD.name = "access_token"
WXTOKEN_ACCESS_TOKEN_FIELD.full_name = ".WXToken.access_token"
WXTOKEN_ACCESS_TOKEN_FIELD.number = 1
WXTOKEN_ACCESS_TOKEN_FIELD.index = 0
WXTOKEN_ACCESS_TOKEN_FIELD.label = 2
WXTOKEN_ACCESS_TOKEN_FIELD.has_default_value = false
WXTOKEN_ACCESS_TOKEN_FIELD.default_value = ""
WXTOKEN_ACCESS_TOKEN_FIELD.type = 9
WXTOKEN_ACCESS_TOKEN_FIELD.cpp_type = 9

WXTOKEN_EXPIRES_IN_FIELD.name = "expires_in"
WXTOKEN_EXPIRES_IN_FIELD.full_name = ".WXToken.expires_in"
WXTOKEN_EXPIRES_IN_FIELD.number = 2
WXTOKEN_EXPIRES_IN_FIELD.index = 1
WXTOKEN_EXPIRES_IN_FIELD.label = 1
WXTOKEN_EXPIRES_IN_FIELD.has_default_value = false
WXTOKEN_EXPIRES_IN_FIELD.default_value = 0
WXTOKEN_EXPIRES_IN_FIELD.type = 5
WXTOKEN_EXPIRES_IN_FIELD.cpp_type = 1

WXTOKEN_REFRESH_TOKEN_FIELD.name = "refresh_token"
WXTOKEN_REFRESH_TOKEN_FIELD.full_name = ".WXToken.refresh_token"
WXTOKEN_REFRESH_TOKEN_FIELD.number = 3
WXTOKEN_REFRESH_TOKEN_FIELD.index = 2
WXTOKEN_REFRESH_TOKEN_FIELD.label = 1
WXTOKEN_REFRESH_TOKEN_FIELD.has_default_value = false
WXTOKEN_REFRESH_TOKEN_FIELD.default_value = ""
WXTOKEN_REFRESH_TOKEN_FIELD.type = 9
WXTOKEN_REFRESH_TOKEN_FIELD.cpp_type = 9

WXTOKEN_OPENID_FIELD.name = "openid"
WXTOKEN_OPENID_FIELD.full_name = ".WXToken.openid"
WXTOKEN_OPENID_FIELD.number = 4
WXTOKEN_OPENID_FIELD.index = 3
WXTOKEN_OPENID_FIELD.label = 2
WXTOKEN_OPENID_FIELD.has_default_value = false
WXTOKEN_OPENID_FIELD.default_value = ""
WXTOKEN_OPENID_FIELD.type = 9
WXTOKEN_OPENID_FIELD.cpp_type = 9

WXTOKEN_SCOPE_FIELD.name = "scope"
WXTOKEN_SCOPE_FIELD.full_name = ".WXToken.scope"
WXTOKEN_SCOPE_FIELD.number = 5
WXTOKEN_SCOPE_FIELD.index = 4
WXTOKEN_SCOPE_FIELD.label = 1
WXTOKEN_SCOPE_FIELD.has_default_value = false
WXTOKEN_SCOPE_FIELD.default_value = ""
WXTOKEN_SCOPE_FIELD.type = 9
WXTOKEN_SCOPE_FIELD.cpp_type = 9

WXTOKEN_UNIONID_FIELD.name = "unionid"
WXTOKEN_UNIONID_FIELD.full_name = ".WXToken.unionid"
WXTOKEN_UNIONID_FIELD.number = 6
WXTOKEN_UNIONID_FIELD.index = 5
WXTOKEN_UNIONID_FIELD.label = 1
WXTOKEN_UNIONID_FIELD.has_default_value = false
WXTOKEN_UNIONID_FIELD.default_value = ""
WXTOKEN_UNIONID_FIELD.type = 9
WXTOKEN_UNIONID_FIELD.cpp_type = 9

WXTOKEN.name = "WXToken"
WXTOKEN.full_name = ".WXToken"
WXTOKEN.nested_types = {}
WXTOKEN.enum_types = {}
WXTOKEN.fields = {WXTOKEN_ACCESS_TOKEN_FIELD, WXTOKEN_EXPIRES_IN_FIELD, WXTOKEN_REFRESH_TOKEN_FIELD, WXTOKEN_OPENID_FIELD, WXTOKEN_SCOPE_FIELD, WXTOKEN_UNIONID_FIELD}
WXTOKEN.is_extendable = false
WXTOKEN.extensions = {}
WXERROR_ERRCODE_FIELD.name = "errcode"
WXERROR_ERRCODE_FIELD.full_name = ".WXError.errcode"
WXERROR_ERRCODE_FIELD.number = 1
WXERROR_ERRCODE_FIELD.index = 0
WXERROR_ERRCODE_FIELD.label = 2
WXERROR_ERRCODE_FIELD.has_default_value = false
WXERROR_ERRCODE_FIELD.default_value = 0
WXERROR_ERRCODE_FIELD.type = 5
WXERROR_ERRCODE_FIELD.cpp_type = 1

WXERROR_ERRMSG_FIELD.name = "errmsg"
WXERROR_ERRMSG_FIELD.full_name = ".WXError.errmsg"
WXERROR_ERRMSG_FIELD.number = 2
WXERROR_ERRMSG_FIELD.index = 1
WXERROR_ERRMSG_FIELD.label = 1
WXERROR_ERRMSG_FIELD.has_default_value = false
WXERROR_ERRMSG_FIELD.default_value = ""
WXERROR_ERRMSG_FIELD.type = 9
WXERROR_ERRMSG_FIELD.cpp_type = 9

WXERROR.name = "WXError"
WXERROR.full_name = ".WXError"
WXERROR.nested_types = {}
WXERROR.enum_types = {}
WXERROR.fields = {WXERROR_ERRCODE_FIELD, WXERROR_ERRMSG_FIELD}
WXERROR.is_extendable = false
WXERROR.extensions = {}

WXError = protobuf.Message(WXERROR)
WXToken = protobuf.Message(WXTOKEN)

