--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.user_pb')

USER = protobuf.Descriptor();
USER_ID_FIELD = protobuf.FieldDescriptor();
USER_NAME_FIELD = protobuf.FieldDescriptor();
USER_FIRENDLIST_FIELD = protobuf.FieldDescriptor();

USER_ID_FIELD.name = "id"
USER_ID_FIELD.full_name = ".User.id"
USER_ID_FIELD.number = 1
USER_ID_FIELD.index = 0
USER_ID_FIELD.label = 2
USER_ID_FIELD.has_default_value = false
USER_ID_FIELD.default_value = 0
USER_ID_FIELD.type = 13
USER_ID_FIELD.cpp_type = 3

USER_NAME_FIELD.name = "name"
USER_NAME_FIELD.full_name = ".User.name"
USER_NAME_FIELD.number = 2
USER_NAME_FIELD.index = 1
USER_NAME_FIELD.label = 2
USER_NAME_FIELD.has_default_value = false
USER_NAME_FIELD.default_value = ""
USER_NAME_FIELD.type = 9
USER_NAME_FIELD.cpp_type = 9

USER_FIRENDLIST_FIELD.name = "firendlist"
USER_FIRENDLIST_FIELD.full_name = ".User.firendlist"
USER_FIRENDLIST_FIELD.number = 3
USER_FIRENDLIST_FIELD.index = 2
USER_FIRENDLIST_FIELD.label = 3
USER_FIRENDLIST_FIELD.has_default_value = false
USER_FIRENDLIST_FIELD.default_value = {}
USER_FIRENDLIST_FIELD.message_type = USER
USER_FIRENDLIST_FIELD.type = 11
USER_FIRENDLIST_FIELD.cpp_type = 10

USER.name = "User"
USER.full_name = ".User"
USER.nested_types = {}
USER.enum_types = {}
USER.fields = {USER_ID_FIELD, USER_NAME_FIELD, USER_FIRENDLIST_FIELD}
USER.is_extendable = false
USER.extensions = {}

User = protobuf.Message(USER)

